version: '3.8'

services:
  db-postgres:
    image: postgres:15-alpine
    container_name: db-postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-admin}
      POSTGRES_DB: ${POSTGRES_DB:-territorial_db}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - plataforma-net

  ms-configuration:
    build:
      context: ./Backend/configuration
      dockerfile: Dockerfile
    container_name: ms-configuration
    ports:
      - "8003:8003"
    env_file:
      - .env
    depends_on:
      db-postgres:
        condition: service_healthy
    networks:
      - plataforma-net

  ms-ingestion:
    build:
      context: ./Backend/ingestion
      dockerfile: Dockerfile
    container_name: ms-ingestion
    ports:
      - "8001:8001"
    env_file:
      - .env
    volumes:
      - shared_data:/app/storage
    depends_on:
      db-postgres:
        condition: service_healthy
    networks:
      - plataforma-net

  ms-audit-trace:
    build:
      context: ./Backend/audit-trace
      dockerfile: Dockerfile
    container_name: ms-audit-trace
    ports:
      - "8002:8002"
    env_file:
      - .env
    depends_on:
      db-postgres:
        condition: service_healthy
    networks:
      - plataforma-net

  ms-transformation:
    build:
      context: ./Backend/transformation
      dockerfile: Dockerfile
    container_name: ms-transformation
    ports:
      - "8004:8004"
    env_file:
      - .env
    volumes:
      - shared_data:/app/storage
    depends_on:
      db-postgres:
        condition: service_healthy
    networks:
      - plataforma-net

  ms-analytics:
    build:
      context: ./Backend/analytics
      dockerfile: Dockerfile
    container_name: ms-analytics
    ports:
      - "8005:8005"
    env_file:
      - .env
    volumes:
      - shared_data:/app/storage
    depends_on:
      db-postgres:
        condition: service_healthy
    networks:
      - plataforma-net

  bff-gateway:
    build:
      context: ./Backend/gateway
      dockerfile: Dockerfile
    container_name: bff-gateway
    ports:
      - "8000:8000"
      - "8080:8000"
    depends_on:
      - ms-configuration
      - ms-ingestion
      - ms-audit-trace
      - ms-transformation
      - ms-analytics
    networks:
      - plataforma-net

  frontend-web:
    build:
      context: ./Frontend/Frontend-Web
      dockerfile: Dockerfile
    container_name: frontend-web
    ports:
      - "5173:5173"
    volumes:
      - ./Frontend/Frontend-Web:/app
      - /app/node_modules
    command: sh -c "rm -rf node_modules/.vite && npm install && node ./node_modules/vite/bin/vite.js --host"
    depends_on:
      - bff-gateway
    networks:
      - plataforma-net

networks:
  plataforma-net:
    driver: bridge

volumes:
  pgdata:
  shared_data:
