version: '3.8'

services:
  db_postgres:
    image: postgres:15-alpine
    container_name: db_postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-admin}
      POSTGRES_DB: ${POSTGRES_DB:-territorial_db}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - plataforma-net

  ms_configuration:
    build: 
      context: ./Backend/configuration
      dockerfile: Dockerfile
    container_name: ms_configuration
    ports:
      - "8003:8003"
    env_file:
      - .env
    depends_on:
      db_postgres:
        condition: service_healthy
    networks:
      - plataforma-net

  ms_ingestion:
    build: 
      context: ./Backend/ingestion
      dockerfile: Dockerfile
    container_name: ms_ingestion
    ports:
      - "8001:8001"
    env_file:
      - .env
    depends_on:
      db_postgres:
        condition: service_healthy
    networks:
      - plataforma-net

  ms_audit-trace:
    build: 
      context: ./Backend/audit-trace
      dockerfile: Dockerfile
    container_name: ms_audit-trace
    ports:
      - "8002:8002"
    env_file:
      - .env
    depends_on:
      db_postgres:
        condition: service_healthy
    networks:
      - plataforma-net

  bff-gateway:
    build: 
      context: ./Backend/gateway
      dockerfile: Dockerfile
    container_name: bff-gateway
    ports:
      - "8000:8000"
      - "8080:8000"
    depends_on:
      - ms_configuration
      - ms_ingestion
      - ms_audit-trace
    networks:
      - plataforma-net

  frontend_web:
    build:
      context: ./Frontend/Territorial-Web
      dockerfile: Dockerfile
    container_name: frontend_web
    ports:
      - "5173:5173"
    depends_on:
      - bff-gateway
    networks:
      - plataforma-net

networks:
  plataforma-net:
    driver: bridge

volumes:
  pgdata:
